### ISSUE TITLE
Ajout/suppression d'un tag

### ISSUE THREAD

**Issue by Double-i** [Note-thing/frontend#10]
- [x] L'utilisateur peut ajouter un tag à une note
    - [x] Si le tag est nouveau, on envoie une requête au backend
    - [x] Si le tag est déjà présent, rien ne se passe
- [x] L'utilisateur peut supprimer un tag

**Comment by GODOmegaPi** [comment]
Est-ce que l'on parle ici uniquement de l'UI/UX ou aussi des appels à l'API pour gérer la récupération, l'ajout et la suppression des tags ?

**Comment by EricB2A** [comment]
Il s'agit de tâches qui définissent le MVP, et qui comprennent donc l'intégration avec l'API.
