### ISSUE TITLE
Login integration with backend

### ISSUE THREAD

**Issue by EricB2A** [Note-thing/frontend#2]
- [x] page création de compte
- [x] page login
- [x] récupération et stockage du token jwt
- [x] envoi du token jwt dans les requêtes

**Comment by EricB2A** [comment]
@OvichHeigVD je sais pas si tu as déjà commencé cette tâche, sinon tu peux me la laisser.

**Comment by OvichHeigVD** [comment]
Non j ai rien commencé encore. Mais la c est la partie frontend. Ecrit moi au besoin
