### ISSUE TITLE
Créer une fonction utilisaire de debounce

### ISSUE THREAD

**Issue by Double-i** [Note-thing/frontend#26]
Actuellement, lors de màj du nom d'une note ou lors de l'édition d'une note. L'API est matraqué par les requêtes à chaque changement. Pour palier à ce problème, il faudrait une méthode de `debounce`. Une première version (https://www.freecodecamp.org/news/javascript-debounce-example/) est disponible dans `src/utils/utils.js` mais ne semble pas fonctionner comme désiré.

```js
export function debounceInput(cb, timeout = 1000) {
    let timer;
    return (...args) => {
        console.log("test")
        clearTimeout(timer);
        timer = setTimeout(() => { cb.apply(this, args); }, timeout);
    };
}
// On appelle debounceInput qui nous retourne une fonction. On utilise cette fonction à chaque keyPressed de l'utilisateur.
// le clearTimeout permet d'annuler les appels plus anciens (afin d'envoyer une fois la version la plus récente. Ce mécanisme fonctionne grâce à la closure - timer)
```
Elle utilise une closure pour annuler les requetes précédentes (clearTimeout) sauf que debounceInput est rappelée à chaque re-render et donc le timer est écrasé à chaque fois.... Il faut trouver une solution pour faire en sorte qu'appeler une seul est unique fois debounceInput.

**Comment by Double-i** [comment]
Finalement, sortant la variable contenant la fonction de debounce en dehors du composant fonctionnel cela semble fonctionner.

@Ovich Pourrais-tu jeter un oeil tout de même ? 🙏 . Il y a peut moyen de faire quelque chose avec useCallback

**Comment by Double-i** [comment]
Vu avec @Ovich, Il faudrait essayer d'utiliser d'utilise également useMemo

**Comment by OvichHeigVD** [comment]
Une version semble bien fonctionner en utilisant le useCallback

**Comment by OvichHeigVD** [comment]
` const debounceTitle = useCallback(debounceInput(async (value) => {
        try {
            const note = await Patch(`/notes/${notes.note.id}`, { title: value });
            const oldNote = notes.note;
            noteDispatch({ type: 'update_note', note: { ...oldNote, ...note } });
        } catch (err) {
            mainDispatch({
                type: 'dialog',
                dialog: { id: 'update_name_note', is_open: true }
            });
        }
    }), [notes, noteDispatch, mainDispatch, debounceInput]);`
