### ISSUE TITLE
NoteContext - Integration avec backend API

### ISSUE THREAD

**Issue by OvichHeigVD** [Note-thing/frontend#28]
Fetch des données de NoteContext -> NoteContext sera responsable de récuperer des données necessaires aux components consomateurs de NoteContext. 
Restoration de l'état de NoteContext suite au refresh -> basé sur url
Mise à jour du context suite au changement d'url

**Comment by Double-i** [comment]
@OvichHeigVD @Ovich C'est terminé cette issue ?
