### ISSUE TITLE
Editeur

### ISSUE THREAD

**Issue by Double-i** [Note-thing/frontend#3]
- [x] Créer  la "vue" éditeur
- [x] Créer la "vue" preview
- [x] Créer la "vue" splitter
- [x] Lorsque l'utilisateur change quelque chose dans l'éditeur on voit les changement dans la preview
- [x] Tests
- [x] Intégration avec le backend 
   - [x] Autosave

**Comment by Double-i** [comment]
@OvichHeigVD  Du coup si elle te semble ok tu peux close ton issue et la mettre dans done dans Project->kanban

**Comment by OvichHeigVD** [comment]
Pas vraiment car il y a la partie integration avec back end, qq tests, auto save... qui restent en suspends
