### ISSUE TITLE
Irreproductible: problème d'affichage du nom et prénom du compte utilisateur actuellement connecté

### ISSUE THREAD

**Issue by Double-i** [Note-thing/frontend#65]
J'avais effectivement vu quelque chose qui plantait dans une ancienne version mais maintenant je n'arrive pas à reproduire le bug, @GODOmegaPi  peux-tu confirmer que c'est toujours d'actualité ? Si ce n'est plus le cas tu peux directement close cette issue

**Comment by GODOmegaPi** [comment]
Effectivement, ce problème a été résolus avec les dernier commits
