### ISSUE TITLE
irreproductible:  Problème de redirection avec l'url mal formatée

### ISSUE THREAD

**Issue by Double-i** [Note-thing/frontend#66]
Problème de redirection avec l'url mal formatée http://localhost:3000//signin

Il y avait un bug avec la redirection lorsdu signin lorsqu'il y avait des mauvais cred mais je sais pas si c'est related à celle la. 

@GODOmegaPi  Peux tu confirmer que c'est toujours d'actualité et dire autrement comment la reproduire. Si ce n'est plus d'actualité tu peux fermer cette issue directement

**Comment by GODOmegaPi** [comment]
Effectivement, le problème n'est pas survenu à nouveau. Certainement que cela à dû être corrigé dans un commit mais pas référencé à cette issue.
